# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
exclude: '^(\.tox|ci/templates|\.bumpversion\.cfg)(/|$)'
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: master
    hooks:
      - id: black
