# Config file for automatic testing at travis-ci.org
env:
  global:
    - CANVAS_URL=https://canvas.harvard.edu/
language: python
python:
  - 3.8

before_script:
   - pipenv install --dev --ignore-pipfile --deploy

script:
  - skip

deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script: pipenv run python submit.py
